id: anwio_br30_e26_rgb_cct_13w_light_bulb
name: Anwio BR30 E26 RGBWW 13 Watt Light Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/anwio-br30-top-down.jpg
docs_url: https://devices.esphome.io/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/
featured_components:
- id: device
  component_id: light.rgbct
  fields:
    color_interlock: true
    cold_white_color_temperature: 6200K
    warm_white_color_temperature: 2000K
    color_temperature: output_white_temp
    id: device
    name: Light
- id: output_white_temp
  component_id: output.libretiny_pwm
  fields:
    inverted:
      value: true
      locked: true
    id: output_white_temp
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    device_class: duration
    id: sensor_uptime_1
    name: Uptime
featured_bundles:
- id: device_setup
  name: Light (full setup)
  component_ids:
  - output_white_temp
  - device
source:
  type: esphome-devices
  remote_id: Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 89dbba60bad778bf9127cb4d8ffea107591c5c4385def31c65a1ecea1b0ac804
