id: oyajia_led_ceiling_light_as105
name: Oyajia LED Ceiling Light (AS105)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Oyajia-LED-Ceiling-light-AS105/AS105.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Oyajia-LED-Ceiling-light-AS105/pinout.png
docs_url: https://devices.esphome.io/devices/Oyajia-LED-Ceiling-light-AS105/
featured_components:
- id: white_light
  component_id: light.cwww
  fields:
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2800 K
    constant_brightness: true
    id: white_light
    name: White Light
- id: color_light
  component_id: light.beken_spi_led_strip
  fields:
    chipset: WS2812
    num_leds: 60
    rgb_order: GRB
    id: color_light
    name: Color Light
source:
  type: esphome-devices
  remote_id: Oyajia-LED-Ceiling-light-AS105
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Oyajia-LED-Ceiling-light-AS105/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 1d2452f856bc69d6313d72dc6bf1407addcc7c5cd82a5f9c009abc0a8c8e915b
