id: jdong_x6060_lamp
name: JDONG X6060-450 ceiling light
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/JDONG-X6060-lamp/jdong_x6060.jpeg
docs_url: https://devices.esphome.io/devices/JDONG-X6060-lamp/
featured_components:
- id: light_rgbww
  component_id: light.rgbww
  fields:
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    id: light_rgbww
    name: light_rgbww
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    type: seconds
    id: sensor_uptime_1
    name: Uptime Sensor
source:
  type: esphome-devices
  remote_id: JDONG-X6060-lamp
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/JDONG-X6060-lamp/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 9f5e28aeff370f957cd5e299e8cda6e625097080d18540c26695be75a947a6ff
