id: kincony_as
name: KinCony-AS (ESP32 Voice Assistant)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-AS/KinCony-AS-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-AS/KinCony-AS-5.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-AS/KinCony-AS-7.jpg
pins:
- gpio: 4
  available: false
  occupied_by: va_mic
- gpio: 16
  available: false
  occupied_by: on board light
docs_url: https://devices.esphome.io/devices/KinCony-AS/
featured_components:
- id: led_ww
  component_id: light.esp32_rmt_led_strip
  fields:
    rgb_order: RGB
    pin:
      value: 16
      locked: true
    num_leds: 1
    chipset: ws2812
    id: led_ww
    name: on board light
- id: va_mic
  component_id: microphone.i2s_audio
  fields:
    adc_type: external
    i2s_din_pin:
      value: 4
      locked: true
    channel: left
    pdm: false
    bits_per_sample: 32 bit
    id: va_mic
    name: va_mic
source:
  type: esphome-devices
  remote_id: KinCony-AS
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-AS/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 07941fce5c65cac09a8ef83b9d23db6c77a9917718e82532b261e15579886e33
