id: ledvance_e27_rgbw
name: LEDVANCE E27 RGBW Light 806lm
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231t-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDVANCE-E27-RGBW/ledvance-e27-rgbw.jpg
docs_url: https://devices.esphome.io/devices/LEDVANCE-E27-RGBW/
featured_components:
- id: light_rgbw
  component_id: light.rgbw
  fields:
    color_interlock: true
    id: light_rgbw
    name: None
source:
  type: esphome-devices
  remote_id: LEDVANCE-E27-RGBW
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LEDVANCE-E27-RGBW/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 90dd4887566ca965b435facec483e083e5595f5ff0029bb623aae97802a580a5
