id: geeni_4_outlet_surge_strip
name: Geeni 4-Outlet Surge Strip
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Geeni-4-outlet-surge-strip/geeni4.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Geeni-4-outlet-surge-strip/20251115_163733.jpg
tags:
- relay
- compact
docs_url: https://devices.esphome.io/devices/Geeni-4-outlet-surge-strip/
featured_components:
- id: switch_1
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_ON
    id: switch_1
    name: Outlet 1
- id: switch_2
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_ON
    id: switch_2
    name: Outlet 2
- id: switch_3
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_ON
    id: switch_3
    name: Outlet 3
- id: switch_4
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_ON
    id: switch_4
    name: Outlet 4
source:
  type: esphome-devices
  remote_id: Geeni-4-outlet-surge-strip
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Geeni-4-outlet-surge-strip/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 9f305d359bea1c69fd2eef2bb14b0582cf73bdab67f0072b0011397899fc4843
