id: esp32_s3_4_0_inch_smart_display
name: ESP32-S3 4.0 Inch Smart Display
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/ESP32-S3-4.0-Inch-Smart-Display.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/ESP32-S3-4.0-Inch-Smart-Display_animation.jpg
pins:
- gpio: 1
  available: false
  occupied_by: $device_name Relay 3
- gpio: 2
  available: false
  occupied_by: $device_name Relay 2
- gpio: 16
  available: false
  occupied_by: display.st7701s
- gpio: 17
  available: false
  occupied_by: display.st7701s
- gpio: 18
  available: false
  occupied_by: display.st7701s
- gpio: 21
  available: false
  occupied_by: display.st7701s
- gpio: 38
  available: false
  occupied_by: backlight
- gpio: 39
  available: false
  occupied_by: display.st7701s
- gpio: 40
  available: false
  occupied_by: $device_name Relay 1
docs_url: https://devices.esphome.io/devices/ESP32-S3-4.0-Inch-Smart-Display/
featured_components:
- id: display_st7701s_1
  component_id: display.st7701s
  fields:
    color_order: RGB
    cs_pin:
      value: 39
      locked: true
    de_pin:
      value: 18
      locked: true
    hsync_pin:
      value: 16
      locked: true
    vsync_pin:
      value: 17
      locked: true
    pclk_pin:
      value: 21
      locked: true
    data_rate: 40MHz
    id: display_st7701s_1
    name: St7701S 1
- id: backlight
  component_id: output.ledc
  fields:
    pin:
      value: 38
      locked: true
    id: backlight
- id: sensor_wifi
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    entity_category: diagnostic
    id: sensor_wifi
    name: $device_name WiFi Signal
- id: uptime_sensor
  component_id: sensor.uptime
  fields:
    update_interval: 15s
    entity_category: diagnostic
    id: uptime_sensor
    name: $device_name Uptime
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 40
      locked: true
    id: relay1
    name: $device_name Relay 1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 2
      locked: true
    id: relay2
    name: $device_name Relay 2
- id: relay3
  component_id: switch.gpio
  fields:
    pin:
      value: 1
      locked: true
    id: relay3
    name: $device_name Relay 3
source:
  type: esphome-devices
  remote_id: ESP32-S3-4.0-Inch-Smart-Display
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 197521fbb15e9afc69557a2e7b42ccc2914baa597192d5c45a84468eec041938
