id: makerfabs_ac_dimmer
name: MAKERFABS-AC-Dimmer
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Makerfabs-AC-Dimmer/image_1.jpg
docs_url: https://devices.esphome.io/devices/Makerfabs-AC-Dimmer/
featured_components:
- id: fan_speed_1
  component_id: fan.speed
  fields:
    icon: mdi:lightbulb
    id: fan_speed_1
    name: Kitchen Lights
source:
  type: esphome-devices
  remote_id: Makerfabs-AC-Dimmer
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Makerfabs-AC-Dimmer/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 8c5076e8f635f0761fa22a5c10a237f3d28ea4b1616bf0d594c3137a7f1a3ca5
