id: electriq_iqoolsmart12hp_air_conditioner
name: electriQ IQOOL SMART12HP
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Electriq-IQoolsmart12hp-air-conditioner/electriq_IQOOL-SMART12HP.jpg
docs_url: https://devices.esphome.io/devices/Electriq-IQoolsmart12hp-air-conditioner/
featured_components:
- id: climate_tuya_1
  component_id: climate.tuya
  fields:
    supports_heat: true
    supports_cool: true
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    id: climate_tuya_1
    name: Climate
- id: mode
  component_id: select.tuya
  fields:
    enum_datapoint: 4
    optimistic: true
    id: mode
    name: Mode
- id: fanspeed
  component_id: select.tuya
  fields:
    enum_datapoint: 5
    optimistic: true
    id: fanspeed
    name: Fan Speed
- id: temperatureunit
  component_id: select.tuya
  fields:
    enum_datapoint: 19
    optimistic: true
    id: temperatureunit
    name: Temperature Unit
- id: sensor_tuya_1
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 3
    id: sensor_tuya_1
    name: Current Temperature
- id: switch_tuya_1
  component_id: switch.tuya
  fields:
    switch_datapoint: 101
    id: switch_tuya_1
    name: Sleep Mode
- id: switch_tuya_2
  component_id: switch.tuya
  fields:
    switch_datapoint: 104
    id: switch_tuya_2
    name: Oscillating air paddle
source:
  type: esphome-devices
  remote_id: Electriq-IQoolsmart12hp-air-conditioner
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Electriq-IQoolsmart12hp-air-conditioner/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: d9ffd8072434ce2a2743089215cfe12d2677b19517a7b128cc0912c57af3ef7d
