id: avatto_tuya_wifi_smart_switch
name: AVATTO Tuya WiFi Smart Switch Modul
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/AVATTO-Tuya-WiFi-Smart-Switch/AVATTOTuyaWiFiSmartSwitch.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/AVATTO-Tuya-WiFi-Smart-Switch/Frontside.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/AVATTO-Tuya-WiFi-Smart-Switch/Backside.jpg
docs_url: https://devices.esphome.io/devices/AVATTO-Tuya-WiFi-Smart-Switch/
featured_components:
- id: led
  component_id: light.status_led
  fields:
    internal: true
    id: led
    name: State
source:
  type: esphome-devices
  remote_id: AVATTO-Tuya-WiFi-Smart-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/AVATTO-Tuya-WiFi-Smart-Switch/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 78fed0455ee3ef73fbc1fd14354ce15e73360411fc6cd5ef52b3d9d01f2cd392
