id: bauhn_5_way_powerboard
name: Bauhn (Aldi) 5-way Powerboard AP5W-0624
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cbu
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/bauhn-5-way-powerboard/20240712_102440.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/bauhn-5-way-powerboard/20240712_102657.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/bauhn-5-way-powerboard/20240712_102703.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/bauhn-5-way-powerboard/cbu_module_pinout.png
tags:
- relay
- compact
docs_url: https://devices.esphome.io/devices/bauhn-5-way-powerboard/
featured_components:
- id: sensor_bl0942_1
  component_id: sensor.bl0942
  fields:
    update_interval: 10s
    id: sensor_bl0942_1
    name: Bl0942 1
- id: relay_1
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    id: relay_1
    name: '1'
- id: relay_2
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    id: relay_2
    name: '2'
- id: relay_3
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    id: relay_3
    name: '3'
- id: relay_4
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    id: relay_4
    name: '4'
- id: relay_5
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    id: relay_5
    name: '5'
source:
  type: esphome-devices
  remote_id: bauhn-5-way-powerboard
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/bauhn-5-way-powerboard/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 8dcef732e1b47c1b0bda56485d1bff6fc5a098e77188df2ab34c079915e8c746
