id: tuya_wifi_smart_switch_sb2s
name: Tuya WiFi Smart Switch (CB2S WHD06 v.1.2)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/Tuya-WiFi-Smart-Switch-SB2S-front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/Tuya-WiFi-Smart-Switch-SB2S-pcb-front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/Tuya-WiFi-Smart-Switch-SB2S-pcb-back.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/Tuya-WiFi-Smart-Switch-SB2S-submodule-front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/Tuya-WiFi-Smart-Switch-SB2S-submodule-back.jpg
docs_url: https://devices.esphome.io/devices/Tuya-WiFi-Smart-Switch-SB2S/
featured_components:
- id: relay
  component_id: switch.output
  fields:
    restore_mode: ALWAYS_OFF
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: Tuya-WiFi-Smart-Switch-SB2S
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-WiFi-Smart-Switch-SB2S/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 459377a31efdf0df1a4ac94802e5b46333558cda43f7ba3643631bcb41e4eaf8
