id: aubess_wifi_smart_switch
name: Aubess WiFi Smart Switch (CB2S)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-WiFi-Smart-Switch/Aubess-WiFi-Smart-Switch.jpg
docs_url: https://devices.esphome.io/devices/Aubess-WiFi-Smart-Switch/
featured_components:
- id: relay
  component_id: switch.output
  fields:
    restore_mode: ALWAYS_OFF
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: Aubess-WiFi-Smart-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Aubess-WiFi-Smart-Switch/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 3a77d5dc6e3a2add815606648b571e6502518c8588152ece6177e7fcad72f212
