id: kincony_aio
name: KinCony-AIO Hybrid (ESP32-S3 ALL IN ONE Removable Relay board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-AIO/AIO-Hybrid-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-AIO/AIO-Hybrid_diagram.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: AIO_hybrid-io0
- gpio: 1
  available: false
  occupied_by: AIO_hybrid-input02
- gpio: 2
  available: false
  occupied_by: AIO_hybrid-input03
- gpio: 3
  available: false
  occupied_by: AIO_hybrid-output01
- gpio: 4
  available: false
  occupied_by: AIO_hybrid-output02
- gpio: 5
  available: false
  occupied_by: AIO_hybrid-output03
- gpio: 6
  available: false
  occupied_by: AIO_hybrid-output04
- gpio: 7
  available: false
  occupied_by: AIO_hybrid-output05
- gpio: 8
  available: false
  occupied_by: AIO_hybrid-input09
- gpio: 9
  available: false
  occupied_by: AIO_hybrid-input10
- gpio: 10
  available: false
  occupied_by: AIO_hybrid-input11
- gpio: 11
  available: false
  occupied_by: AIO_hybrid-input12
- gpio: 21
  available: false
  occupied_by: My Light IO21
- gpio: 40
  available: false
  occupied_by: AIO_hybrid-433M
- gpio: 41
  available: false
  occupied_by: Ethernet CS
- gpio: 42
  available: false
  occupied_by: Ethernet CLK
- gpio: 43
  available: false
  occupied_by: Ethernet MOSI
- gpio: 44
  available: false
  occupied_by: Ethernet MISO
docs_url: https://devices.esphome.io/devices/KinCony-AIO/
featured_components:
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO42
      locked: true
    mosi_pin:
      value: GPIO43
      locked: true
    miso_pin:
      value: GPIO44
      locked: true
    cs_pin:
      value: GPIO41
      locked: true
    interrupt_pin:
      value: GPIO2
      locked: true
    reset_pin:
      value: GPIO1
      locked: true
- id: aio_hybrid_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input01
    name: AIO_hybrid-input01
- id: aio_hybrid_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input02
    name: AIO_hybrid-input02
- id: aio_hybrid_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input03
    name: AIO_hybrid-input03
- id: aio_hybrid_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input04
    name: AIO_hybrid-input04
- id: aio_hybrid_input05
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input05
    name: AIO_hybrid-input05
- id: aio_hybrid_input06
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input06
    name: AIO_hybrid-input06
- id: aio_hybrid_input07
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input07
    name: AIO_hybrid-input07
- id: aio_hybrid_input08
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input08
    name: AIO_hybrid-input08
- id: aio_hybrid_input09
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input09
    name: AIO_hybrid-input09
- id: aio_hybrid_input10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input10
    name: AIO_hybrid-input10
- id: aio_hybrid_input11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input11
    name: AIO_hybrid-input11
- id: aio_hybrid_input12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_input_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: aio_hybrid_input12
    name: AIO_hybrid-input12
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: false
      locked: true
    id: binary_sensor_gpio_13
    name: AIO_hybrid-433M
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: false
      locked: true
    id: binary_sensor_gpio_14
    name: AIO_hybrid-io0
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    gamma_correct: 1.0
    output: dimmer1
    id: light_monochromatic_1
    name: dimmer-1
- id: light_monochromatic_2
  component_id: light.monochromatic
  fields:
    gamma_correct: 1.0
    output: dimmer2
    id: light_monochromatic_2
    name: dimmer-2
- id: light_monochromatic_3
  component_id: light.monochromatic
  fields:
    gamma_correct: 1.0
    output: dimmer3
    id: light_monochromatic_3
    name: dimmer-3
- id: light_monochromatic_4
  component_id: light.monochromatic
  fields:
    gamma_correct: 1.0
    output: dimmer4
    id: light_monochromatic_4
    name: dimmer-4
- id: light_esp32_rmt_led_strip_1
  component_id: light.esp32_rmt_led_strip
  fields:
    rgb_order: GRB
    pin:
      value: 21
      locked: true
    num_leds: 20
    chipset: ws2812
    id: light_esp32_rmt_led_strip_1
    name: My Light IO21
- id: dimmer1
  component_id: output.mcp4728
  fields:
    channel: A
    vref: vdd
    power_down: normal
    id: dimmer1
- id: dimmer2
  component_id: output.mcp4728
  fields:
    channel: B
    vref: vdd
    power_down: normal
    id: dimmer2
- id: dimmer3
  component_id: output.mcp4728
  fields:
    channel: C
    vref: vdd
    power_down: normal
    id: dimmer3
- id: dimmer4
  component_id: output.mcp4728
  fields:
    channel: D
    vref: vdd
    power_down: normal
    id: dimmer4
- id: sensor_adc_1
  component_id: sensor.adc
  fields:
    pin:
      value: 5
      locked: true
    update_interval: 55s
    attenuation: 11db
    id: sensor_adc_1
    name: AIO_hybrid A1 Voltage
- id: sensor_adc_2
  component_id: sensor.adc
  fields:
    pin:
      value: 7
      locked: true
    update_interval: 55s
    attenuation: 11db
    id: sensor_adc_2
    name: AIO_hybrid A2 Voltage
- id: sensor_adc_3
  component_id: sensor.adc
  fields:
    pin:
      value: 6
      locked: true
    update_interval: 55s
    unit_of_measurement: mA
    attenuation: 11db
    id: sensor_adc_3
    name: AIO_hybrid A3 Current
- id: sensor_adc_4
  component_id: sensor.adc
  fields:
    pin:
      value: 4
      locked: true
    update_interval: 55s
    unit_of_measurement: mA
    attenuation: 11db
    id: sensor_adc_4
    name: AIO_hybrid A4 Current
- id: aio_hybrid_output01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_output_1
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: aio_hybrid_output01
    name: AIO_hybrid-output01
- id: aio_hybrid_output02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_output_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: aio_hybrid_output02
    name: AIO_hybrid-output02
- id: aio_hybrid_output03
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_output_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: aio_hybrid_output03
    name: AIO_hybrid-output03
- id: aio_hybrid_output04
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_output_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: aio_hybrid_output04
    name: AIO_hybrid-output04
- id: aio_hybrid_output05
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_output_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: aio_hybrid_output05
    name: AIO_hybrid-output05
featured_bundles:
- id: light_monochromatic_1_setup
  name: dimmer-1 (full setup)
  component_ids:
  - dimmer1
  - light_monochromatic_1
- id: light_monochromatic_2_setup
  name: dimmer-2 (full setup)
  component_ids:
  - dimmer2
  - light_monochromatic_2
- id: light_monochromatic_3_setup
  name: dimmer-3 (full setup)
  component_ids:
  - dimmer3
  - light_monochromatic_3
- id: light_monochromatic_4_setup
  name: dimmer-4 (full setup)
  component_ids:
  - dimmer4
  - light_monochromatic_4
source:
  type: esphome-devices
  remote_id: KinCony-AIO
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-AIO/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 45c42e7fc2c6a5b0d8e9bac576cf802882c6e7aefe78a55f7d6ed6ff534f21eb
