id: globe_electric_wi_fi_smart_plug_50329
name: Globe Electric Wi-Fi Smart Plug 50359
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe2.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe3.jpg
tags:
- relay
- compact
docs_url: https://devices.esphome.io/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/
featured_components:
- id: led
  component_id: light.status_led
  fields:
    internal: true
    id: led
    name: led
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    unit_of_measurement: minutes
    id: sensor_uptime_1
    name: Uptime
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Signal
- id: outlet
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-us
    id: outlet
    name: Outlet
source:
  type: esphome-devices
  remote_id: Globe-Electric-Wi-Fi-Smart-Plug-50329
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 1253d49929d20ed426586cbdcb92cdf105070a83deda19d5c2c17757fed33df1
