id: aubess_mini_smart_switch_cb2s_v_2022
name: Aubess WiFi Smart Switch (CB2S) V.2022
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/Aubess-Mini-Smart-Switch-V2022-Product-image.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/Aubess-Mini-Smart-Switch-V2022-General-View.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/Aubess-Mini-Smart-Switch-V2022-bottom.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/Aubess-Mini-Smart-Switch-V2022-Pinout1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/Aubess-Mini-Smart-Switch-V2022-Pinout2.jpg
docs_url: https://devices.esphome.io/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/
featured_components:
- id: relay
  component_id: switch.output
  fields:
    restore_mode: ALWAYS_OFF
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: Aubess-Mini-Smart-Switch-CB2S-V-2022
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Aubess-Mini-Smart-Switch-CB2S-V-2022/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 9bf660a416cda83d9bed050e4fee4b58bb124aa73c7c0b9409e66d71458612d5
