id: treatlife_ds02s
name: TreatLife DS02S Single Pole Dimmer
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/TreatLife-DS02S/Treatlife-DS02S.png
docs_url: https://devices.esphome.io/devices/TreatLife-DS02S/
featured_components:
- id: light_tuya_1
  component_id: light.tuya
  fields:
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 100
    max_value: 1000
    id: light_tuya_1
    name: Tuya 1
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: WiFi Signal
source:
  type: esphome-devices
  remote_id: TreatLife-DS02S
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/TreatLife-DS02S/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: be155dc6246ae3e4c7d770cbfa66b6a3024498405c223c21efee09d9e8973897
