id: steren_rgbww_desk_lamp
name: Steren RGBWW Desk Lamp
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Steren-RGBWW-Desk-Lamp/box.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Steren-RGBWW-Desk-Lamp/open.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Steren-RGBWW-Desk-Lamp/pcb1.jpg
docs_url: https://devices.esphome.io/devices/Steren-RGBWW-Desk-Lamp/
featured_components:
- id: rgb_light
  component_id: light.rgbww
  fields:
    restore_mode: ALWAYS_OFF
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    color_interlock: true
    id: rgb_light
    name: Light
source:
  type: esphome-devices
  remote_id: Steren-RGBWW-Desk-Lamp
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Steren-RGBWW-Desk-Lamp/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 2b0b061a101feb9fc45a21f1f20f1ae4d3457a715ab1c22131a5f445a3c1e734
