id: martin_jerry_rp_fc01
name: MJ-RP-FC01 Ceiling Fan Controller
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Martin-Jerry-RP-FC01/MJ-RP-FC01.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Martin-Jerry-RP-FC01/rp-fc01-board.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Martin-Jerry-RP-FC01/rp-fc01-flash-diagram.png
docs_url: https://devices.esphome.io/devices/Martin-Jerry-RP-FC01/
featured_components:
- id: mcu_fan
  component_id: fan.tuya
  fields:
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    id: mcu_fan
    name: Ceiling Fan
- id: fan_mode_select
  component_id: select.tuya
  fields:
    enum_datapoint: 11
    id: fan_mode_select
    name: Fan Mode
source:
  type: esphome-devices
  remote_id: Martin-Jerry-RP-FC01
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Martin-Jerry-RP-FC01/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: a228e4d40d29860be3ab7b05c25e8f178fdac746585fb6e05b6c50a51e938484
