id: ledvance_smart_table_frame_multicolor
name: LEDVANCE SMART+ TABLE FRAME MULTICOLOR
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb3l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR/product.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR/product-disassembled.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR/product-pcb.jpg
docs_url: https://devices.esphome.io/devices/LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR/
featured_components:
- id: light_rgbw_1
  component_id: light.rgbw
  fields:
    restore_mode: RESTORE_AND_ON
    color_interlock: true
    gamma_correct: 1.0
    id: light_rgbw_1
    name: Light
source:
  type: esphome-devices
  remote_id: LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LEDVANCE-SMART+-TABLE-FRAME-MULTICOLOR/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: c5937a18411336d3677942de2b2095f044b430005f5b09bd378a68c493fc781b
