id: genvex_nibe_alphainnotec_heat_recovery_ventilation
name: Genvex ECO 375, Nibe ERS 10-500, Alpha-Innotec LG 300 ECO B(E) ventilation
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/ECO-375-mark2-lukket.jpg
pins:
- gpio: 0
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
docs_url: https://devices.esphome.io/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/
featured_components:
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    clk_mode:
      value: GPIO0_IN
      locked: true
    phy_addr:
      value: 0
      locked: true
- id: binary_sensor_modbus_controller_1
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 1
    id: binary_sensor_modbus_controller_1
    name: Alarm General Error
- id: binary_sensor_modbus_controller_2
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: opening
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 2
    id: binary_sensor_modbus_controller_2
    name: Bypass1
- id: binary_sensor_modbus_controller_3
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 4
    id: binary_sensor_modbus_controller_3
    name: Relay R9
- id: binary_sensor_modbus_controller_4
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 8
    id: binary_sensor_modbus_controller_4
    name: Alarm Filter
- id: binary_sensor_modbus_controller_5
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 16
    id: binary_sensor_modbus_controller_5
    name: Alarm Frost
- id: binary_sensor_modbus_controller_6
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 64
    id: binary_sensor_modbus_controller_6
    name: Alarm Hygrostat
- id: binary_sensor_modbus_controller_7
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 128
    id: binary_sensor_modbus_controller_7
    name: Alarm Device Stopped
- id: binary_sensor_modbus_controller_8
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: opening
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 1024
    id: binary_sensor_modbus_controller_8
    name: Bypass2
- id: binary_sensor_modbus_controller_9
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 4096
    disabled_by_default: true
    id: binary_sensor_modbus_controller_9
    name: Relay R8
- id: binary_sensor_modbus_controller_10
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 8192
    disabled_by_default: true
    id: binary_sensor_modbus_controller_10
    name: Relay R2 Electric Reheating
- id: binary_sensor_modbus_controller_11
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 16384
    disabled_by_default: true
    id: binary_sensor_modbus_controller_11
    name: Relay R3 Preheating
- id: button_restart_1
  component_id: button.restart
  fields:
    entity_category: diagnostic
    id: button_restart_1
    name: controller restart
- id: button_safe_mode_1
  component_id: button.safe_mode
  fields:
    entity_category: diagnostic
    id: button_safe_mode_1
    name: controller safe mode boot
- id: number_modbus_controller_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:timer-sand
    address: 14
    unit_of_measurement: h
    value_type: U_WORD
    entity_category: config
    min_value: 1
    max_value: 9
    step: 1
    mode: box
    id: number_modbus_controller_1
    name: Max duration for level 3-4
- id: genvex_speed_in_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-1
    address: 7
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 10
    max_value: 45
    step: 1
    mode: box
    id: genvex_speed_in_1
    name: Level 1 supply
- id: genvex_speed_out_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-1
    address: 10
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 10
    max_value: 45
    step: 1
    mode: box
    id: genvex_speed_out_1
    name: Level 1 extract
- id: genvex_speed_in_2
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-2
    address: 8
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 40
    max_value: 75
    step: 1
    mode: box
    id: genvex_speed_in_2
    name: Level 2 supply
- id: genvex_speed_out_2
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-2
    address: 11
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 40
    max_value: 75
    step: 1
    mode: box
    id: genvex_speed_out_2
    name: Level 2 extract
- id: genvex_speed_in_3
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-3
    address: 9
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 60
    max_value: 85
    step: 1
    mode: box
    id: genvex_speed_in_3
    name: Level 3 supply
- id: genvex_speed_out_3
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-3
    address: 12
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 60
    max_value: 85
    step: 1
    mode: box
    id: genvex_speed_out_3
    name: Level 3 extract
- id: number_modbus_controller_8
  component_id: number.modbus_controller
  fields:
    unit_of_measurement: °C
    icon: mdi:cog-outline
    address: 26
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 20
    step: 1
    mode: box
    id: number_modbus_controller_8
    name: Bypass close external delta
- id: number_modbus_controller_9
  component_id: number.modbus_controller
  fields:
    unit_of_measurement: mo
    icon: mdi:cog-outline
    address: 5
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 12
    step: 1
    mode: box
    disabled_by_default: true
    id: number_modbus_controller_9
    name: Filter change period
- id: genvex_sel
  component_id: select.modbus_controller
  fields:
    icon: mdi:fan
    address: 0
    value_type: U_WORD
    optimistic: true
    id: genvex_sel
    name: Speed
- id: select_modbus_controller_2
  component_id: select.modbus_controller
  fields:
    icon: mdi:cog-outline
    entity_category: config
    address: 41
    value_type: U_WORD
    skip_updates: 24
    disabled_by_default: true
    id: select_modbus_controller_2
    name: Display model
- id: select_modbus_controller_3
  component_id: select.modbus_controller
  fields:
    icon: mdi:cog-outline
    entity_category: config
    address: 16
    value_type: U_WORD
    skip_updates: 24
    disabled_by_default: true
    id: select_modbus_controller_3
    name: Regulation method
- id: genvex_inlet_fan
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:fan
    register_type: read
    address: 9
    unit_of_measurement: '%'
    value_type: U_WORD
    id: genvex_inlet_fan
    name: Inlet fan
- id: genvex_extract_fan
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:fan
    register_type: read
    address: 10
    unit_of_measurement: '%'
    value_type: U_WORD
    id: genvex_extract_fan
    name: Extract fan
- id: sensor_modbus_controller_3
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 0
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    id: sensor_modbus_controller_3
    name: Supply air
- id: sensor_modbus_controller_4
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 2
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    id: sensor_modbus_controller_4
    name: Fresh air
- id: sensor_modbus_controller_5
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 3
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    id: sensor_modbus_controller_5
    name: Exhaust air
- id: genvex_temp_t7
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 6
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    id: genvex_temp_t7
    name: Extract air
- id: sensor_modbus_controller_7
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:debug-step-over
    unit_of_measurement: '%'
    register_type: read
    address: 11
    value_type: U_WORD
    id: sensor_modbus_controller_7
    name: Bypass
- id: genvex_hum
  component_id: sensor.modbus_controller
  fields:
    device_class: humidity
    unit_of_measurement: '%'
    register_type: read
    address: 13
    value_type: U_WORD
    id: genvex_hum
    name: Humidity
- id: genvex_mode
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:speedometer-slow
    register_type: holding
    entity_category: diagnostic
    address: 0
    value_type: U_WORD
    disabled_by_default: true
    bitmask: 2147483647
    id: genvex_mode
    name: Mode (modbus)
- id: sensor_modbus_controller_10
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:alert-circle-outline
    register_type: read
    entity_category: diagnostic
    address: 15
    value_type: U_WORD
    disabled_by_default: true
    bitmask: 2147483647
    id: sensor_modbus_controller_10
    name: Alarm code (DEC)
- id: sensor_modbus_controller_11
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:water-boiler
    register_type: read
    unit_of_measurement: '%'
    address: 5
    value_type: U_WORD
    bitmask: 2147483647
    id: sensor_modbus_controller_11
    name: Reheating
- id: sensor_modbus_controller_12
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:water-boiler
    register_type: read
    unit_of_measurement: '%'
    address: 12
    value_type: U_WORD
    bitmask: 2147483647
    id: sensor_modbus_controller_12
    name: Reheating control
- id: switch_modbus_controller_1
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:water-boiler
    register_type: holding
    address: 1
    bitmask: 1
    id: switch_modbus_controller_1
    name: Reheating
- id: switch_modbus_controller_2
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    register_type: holding
    address: 4
    bitmask: 1
    id: switch_modbus_controller_2
    name: Max duration for level 3-4 enable
- id: switch_modbus_controller_3
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:air-humidifier
    register_type: holding
    address: 6
    bitmask: 1
    id: switch_modbus_controller_3
    name: Humidity control
- id: switch_modbus_controller_4
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 15
    bitmask: 1
    id: switch_modbus_controller_4
    name: Filter change autostop
- id: switch_modbus_controller_5
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 25
    bitmask: 1
    id: switch_modbus_controller_5
    name: Device stop enable
- id: switch_modbus_controller_6
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 45
    bitmask: 1
    id: switch_modbus_controller_6
    name: Calendar mode
- id: switch_modbus_controller_7
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:air-filter
    register_type: holding
    address: 47
    bitmask: 1
    id: switch_modbus_controller_7
    name: Filter reset
source:
  type: esphome-devices
  remote_id: Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 182316d4b3fa783217495e74f5d22020ce3625b89090fe2b8205f403857d99a0
