id: tuya_2_gang_switch_socket
name: Tuya 2 Gang Switch Socket
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231t-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-2-Gang-Switch-Socket/tyna-gpo-switch.png
docs_url: https://devices.esphome.io/devices/Tuya-2-Gang-Switch-Socket/
featured_components:
- id: button_1
  component_id: binary_sensor.gpio
  fields:
    internal: true
    id: button_1
    name: button_1
- id: button_2
  component_id: binary_sensor.gpio
  fields:
    internal: true
    id: button_2
    name: button_2
- id: relay
  component_id: switch.gpio
  fields:
    restore_mode: always on
    icon: mdi:power-socket-au
    id: relay
    name: relay
source:
  type: esphome-devices
  remote_id: Tuya-2-Gang-Switch-Socket
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-2-Gang-Switch-Socket/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: ab80d39c650865d38ae4f4dac38d9bb919f6cd80400b919743af7c6fe3abf9e8
