id: kincony_e16p
name: KinCony E16P POE Ethernet Removable Relay Module
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-E16P/E16P-1_07.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: e16t-output9
- gpio: 1
  available: false
  occupied_by: e16t-output10
- gpio: 2
  available: false
  occupied_by: e16t-output11
- gpio: 3
  available: false
  occupied_by: e16t-output12
- gpio: 4
  available: false
  occupied_by: e16t-output13
- gpio: 5
  available: false
  occupied_by: e16t-output14
- gpio: 6
  available: false
  occupied_by: e16t-output15
- gpio: 7
  available: false
  occupied_by: e16t-output16
- gpio: 17
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
docs_url: https://devices.esphome.io/devices/KinCony-E16P/
featured_components:
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    clk_mode:
      value: GPIO17_OUT
      locked: true
    phy_addr:
      value: 0
      locked: true
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: e16t-input1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: e16t-input2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: e16t-input3
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: e16t-input4
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: e16t-input5
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: e16t-input6
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: e16t-input7
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: e16t-input8
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: e16t-input9
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: e16t-input10
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: e16t-input11
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: e16t-input12
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: e16t-input13
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: e16t-input14
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: e16t-input15
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: e16t-input16
- id: switch_gpio_1
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_1
    name: e16t-output1
- id: switch_gpio_2
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_2
    name: e16t-output2
- id: switch_gpio_3
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_3
    name: e16t-output3
- id: switch_gpio_4
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_4
    name: e16t-output4
- id: switch_gpio_5
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_5
    name: e16t-output5
- id: switch_gpio_6
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_6
    name: e16t-output6
- id: switch_gpio_7
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_7
    name: e16t-output7
- id: switch_gpio_8
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_8
    name: e16t-output8
- id: switch_gpio_9
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_9
    name: e16t-output9
- id: switch_gpio_10
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_10
    name: e16t-output10
- id: switch_gpio_11
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_11
    name: e16t-output11
- id: switch_gpio_12
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_12
    name: e16t-output12
- id: switch_gpio_13
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_13
    name: e16t-output13
- id: switch_gpio_14
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_14
    name: e16t-output14
- id: switch_gpio_15
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_15
    name: e16t-output15
- id: switch_gpio_16
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_16
    name: e16t-output16
source:
  type: esphome-devices
  remote_id: KinCony-E16P
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-E16P/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 0e49ff2242e8e70e32e58d2b7e37b6d30285e972adad8e1ff5263ce41cde496f
