id: aspen_asp_200_smart_window_fan
name: Aspen ASP-200 Smart Window Fan
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp12e
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aspen-ASP-200-Smart-Window-Fan/asp-200.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aspen-ASP-200-Smart-Window-Fan/asp-200-pcb.jpg
docs_url: https://devices.esphome.io/devices/Aspen-ASP-200-Smart-Window-Fan/
featured_components:
- id: fan_tuya_1
  component_id: fan.tuya
  fields:
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 3
    id: fan_tuya_1
    name: Tuya 1
- id: device_name_u_speed
  component_id: select.tuya
  fields:
    enum_datapoint: 3
    optimistic: true
    id: device_name_u_speed
    name: Speed
- id: device_name_u_mode
  component_id: select.tuya
  fields:
    enum_datapoint: 2
    optimistic: true
    id: device_name_u_mode
    name: Mode
- id: device_name_u_temp
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 19
    unit_of_measurement: °F
    id: device_name_u_temp
    name: Temperature
- id: device_name_u_power_switch
  component_id: switch.tuya
  fields:
    switch_datapoint: 1
    id: device_name_u_power_switch
    name: Power
source:
  type: esphome-devices
  remote_id: Aspen-ASP-200-Smart-Window-Fan
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Aspen-ASP-200-Smart-Window-Fan/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 30106bcff542e9024d443580cbeef3348398abe0af9aebf75a12f5aa670e2f91
