id: tuya_smart_plug_20a
name: Tuya Smart Plug 16/20A with Power Monitoring
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/tuya-smart-plug-20.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/hardware-closeup.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/programming.jpg
tags:
- relay
- compact
docs_url: https://devices.esphome.io/devices/Tuya-Smart-Plug-20A/
featured_components:
- id: button_1
  component_id: binary_sensor.gpio
  fields:
    icon: mdi:radiobox-blank
    id: button_1
    name: button_1
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    voltage_divider: 760
    initial_mode: CURRENT
    update_interval: 15s
    change_mode_every: 4
    id: sensor_hlw8012_1
    name: Hlw8012 1
source:
  type: esphome-devices
  remote_id: Tuya-Smart-Plug-20A
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-Smart-Plug-20A/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 986d64fb1c916b99c96ba6a495ab182349d853cf185e4bdd68864fd9750bd3e8
