id: kincony_kc868_ak
name: KinCony KC868-AK
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-AK/kc868-ak.png
pins:
- gpio: 0
  available: false
  occupied_by: ak-input33
- gpio: 1
  available: false
  occupied_by: ak-input34
- gpio: 2
  available: false
  occupied_by: ak-input35
- gpio: 3
  available: false
  occupied_by: ak-input36
- gpio: 4
  available: false
  occupied_by: ak-input29
- gpio: 5
  available: false
  occupied_by: ak-input30
- gpio: 6
  available: false
  occupied_by: ak-input31
- gpio: 7
  available: false
  occupied_by: ak-input32
docs_url: https://devices.esphome.io/devices/KinCony-KC868-AK/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: ak-input1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: ak-input2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: ak-input3
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: ak-input4
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: ak-input5
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: ak-input6
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: ak-input7
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: ak-input8
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: ak-input9
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: ak-input10
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: ak-input11
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: ak-input12
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: ak-input13
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: ak-input14
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: ak-input15
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: ak-input16
- id: binary_sensor_gpio_17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_17
    name: ak-input17
- id: binary_sensor_gpio_18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_18
    name: ak-input18
- id: binary_sensor_gpio_19
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_19
    name: ak-input19
- id: binary_sensor_gpio_20
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_20
    name: ak-input20
- id: binary_sensor_gpio_21
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_21
    name: ak-input21
- id: binary_sensor_gpio_22
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_22
    name: ak-input22
- id: binary_sensor_gpio_23
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_23
    name: ak-input23
- id: binary_sensor_gpio_24
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_3
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_24
    name: ak-input24
- id: binary_sensor_gpio_25
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_25
    name: ak-input25
- id: binary_sensor_gpio_26
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_26
    name: ak-input26
- id: binary_sensor_gpio_27
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_27
    name: ak-input27
- id: binary_sensor_gpio_28
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_28
    name: ak-input28
- id: binary_sensor_gpio_29
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_29
    name: ak-input29
- id: binary_sensor_gpio_30
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_30
    name: ak-input30
- id: binary_sensor_gpio_31
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_31
    name: ak-input31
- id: binary_sensor_gpio_32
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_4
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_32
    name: ak-input32
- id: binary_sensor_gpio_33
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_5
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_33
    name: ak-input33
- id: binary_sensor_gpio_34
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_5
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_34
    name: ak-input34
- id: binary_sensor_gpio_35
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_5
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_35
    name: ak-input35
- id: binary_sensor_gpio_36
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_5
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_36
    name: ak-input36
source:
  type: esphome-devices
  remote_id: KinCony-KC868-AK
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-AK/index.md
  upstream_revision: 0960c5c1fb74b1e9d60829bf911f47b0e8cf2eb1
  content_hash: 6bbc6207b067bffca12a75e84948837d8010cec925761245f59441df08db12b6
